# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from demo import Ui_mainWindow

class Ui_window_proj(object):
    def setupUi(self, window_proj):
        window_proj.setObjectName("window_proj")
        window_proj.resize(1051, 772)
        window_proj.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(window_proj)
        self.centralwidget.setObjectName("centralwidget")
        self.gbox_must = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_must.setGeometry(QtCore.QRect(40, 30, 241, 471))
        self.gbox_must.setFlat(True)
        self.gbox_must.setObjectName("gbox_must")
        self.listWidget = QtWidgets.QListWidget(self.gbox_must)
        self.listWidget.setGeometry(QtCore.QRect(50, 20, 101, 21))
        self.listWidget.setObjectName("listWidget")
        self.gbox_even = QtWidgets.QGroupBox(self.gbox_must)
        self.gbox_even.setGeometry(QtCore.QRect(30, 260, 151, 181))
        self.gbox_even.setObjectName("gbox_even")
        self.radioButton = QtWidgets.QRadioButton(self.gbox_even)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 86, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gbox_even)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 80, 86, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.gbox_ampli = QtWidgets.QGroupBox(self.gbox_must)
        self.gbox_ampli.setGeometry(QtCore.QRect(40, 110, 151, 101))
        self.gbox_ampli.setObjectName("gbox_ampli")
        self.radioButton_6 = QtWidgets.QRadioButton(self.gbox_ampli)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 30, 86, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_5 = QtWidgets.QRadioButton(self.gbox_ampli)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 60, 86, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.textEdit = QtWidgets.QTextEdit(self.gbox_must)
        self.textEdit.setGeometry(QtCore.QRect(50, 60, 104, 21))
        self.textEdit.setObjectName("textEdit")
        self.pbtn_run = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_run.setGeometry(QtCore.QRect(60, 550, 158, 23))
        self.pbtn_run.setObjectName("pbtn_run")
        window_proj.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(window_proj)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1051, 30))
        self.menuBar.setObjectName("menuBar")
        window_proj.setMenuBar(self.menuBar)

        self.retranslateUi(window_proj)
        QtCore.QMetaObject.connectSlotsByName(window_proj)
        self.my_all_connect(window_proj)

    def retranslateUi(self, window_proj):
        _translate = QtCore.QCoreApplication.translate
        window_proj.setWindowTitle(_translate("window_proj", "Proj"))
        self.gbox_must.setTitle(_translate("window_proj", "必填"))
        self.gbox_even.setTitle(_translate("window_proj", "GroupBox"))
        self.radioButton.setText(_translate("window_proj", "RadioButton"))
        self.radioButton_2.setText(_translate("window_proj", "RadioButton"))
        self.gbox_ampli.setTitle(_translate("window_proj", "GroupBox"))
        self.radioButton_6.setText(_translate("window_proj", "RadioButton"))
        self.radioButton_5.setText(_translate("window_proj", "RadioButton"))
        self.pbtn_run.setText(_translate("window_proj", "PushButton"))


    def my_all_connect(self, window_proj):
        from functools import partial
        self.pbtn_run.clicked.connect( partial(self.show_son, window_proj) )

    def show_son(self, window_proj):
        # self.son_window = QtWidgets.QMainWindow()
        # Ui_mainWindow().setupUi(self.son_window)
        # window_proj.setVisible(False)
        # self.son_window.show()

        self.son_window = Ui_mainWindow()
        self.son_window.setupUi(self.son_window)
        window_proj.setVisible(False)
        self.son_window.show()


# 要复制
if __name__ == "__main__":
    app = QtWidgets.QApplication([])  # 传一个空字符串数组
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_window_proj()
    ui.setupUi(mainWindow)
    mainWindow.show()
    exit(app.exec_())
